FROM nginx:alpine
   # Копируем созданную на ПК папку build внутрь контейнера Nginx
   COPY build /usr/share/nginx/html
   EXPOSE 3000
   # Меняем дефолтный порт Nginx на 3000
   RUN sed -i 's/listen[:[:space:]]*80;/listen 3000;/g' /etc/nginx/conf.d/default.conf
   CMD ["nginx", "-g", "daemon off;"]