backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: inventory_api
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: inventory_db
      PORT: 3001
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

frontend:
  build:
    context: .
    dockerfile: Dockerfile.frontend
  container_name: inventory_ui
  restart: always
  ports:
    - "3000:3000"
  depends_on:
    - backend
  deploy:
    resources:
      limits:
        cpus: '0.25'
        memory: 64M